name: 🐞 RAG Time Bug
description: File a bug about RAG Time
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        Please complete the following form to help us assist you.
  - type: textarea
    id: what-happened
    attributes:
      label: Bug Description
      description: What happened?
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of ragtime are you using?
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Which steps should someone take to run into the same error?
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs/Tracbacks
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell